package negocio;
// * this code was generated by Window Builder extension * //

import javax.swing.*;
import java.awt.*;

public class PlacarJogo implements Observer {

  public PlacarJogo() {
  }

  @Override
  public void update(String mensagem) {
    JFrame frame = new JFrame("Placar Do Jogo");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setSize(400, 400);

    JPanel panel = new JPanel(new GridBagLayout());
    GridBagConstraints constraints = new GridBagConstraints();

    // Fill the layout with placeholders
    for (int row = 0; row < 12; row++) {
      for (int col = 0; col < 12; col++) {
        constraints.gridx = col;
        constraints.gridy = row;
        constraints.weightx = 1.0;
        constraints.weighty = 1.0;
        constraints.fill = GridBagConstraints.BOTH;

        Component filler = Box.createRigidArea(new Dimension(0, 0));
        panel.add(filler, constraints);
      }
    }

    constraints.weightx = 0;
    constraints.weighty = 0;
    constraints.fill = GridBagConstraints.NONE;
    constraints.anchor = GridBagConstraints.NORTHWEST;

    JLabel label_0 = new JLabel(mensagem);
    constraints.gridx = 1;
    constraints.gridy = 0;
    constraints.gridwidth = 2;
    constraints.gridheight = 2;
    panel.add(label_0, constraints);

    frame.add(panel);
    frame.setVisible(true);
  }

}
